version: '3.8'

services:
  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    ports:
      - "7999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/etc/nginx/html:ro
    networks:
      - tortank-shared-network

networks:
  tortank-shared-network:
    external: true
