name: Build Docker Containers

on:
  push:
    branches:
      - main
    tags:
      - '*deploy-api*'
      - '*deploy-front*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # This step sets up QEMU, which is a hardware virtualization tool. It allows you to build and 
      # run Docker images for different CPU architectures (e.g., ARM) on the current machine
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # This step sets up Docker Buildx, which is an extended builder for Docker. 
      # It supports multi-architecture builds and cache import/export among other advanced features
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # This step checks out the repository code so that subsequent steps can access it. 
      # It fetches the code from your GitHub repository into the runner
      - name: Checkout repository
        uses: actions/checkout@v3

      # This step logs in to Docker Hub using the provided username and token stored in GitHub Secrets. 
      # This is necessary to push Docker images to your Docker Hub repository
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # This step builds and pushes the backend Docker image. It only runs if the commit message contains 'deploy-api'
      - name: Build and push backend image
        if: contains(github.event.head_commit.message, 'deploy-api')
        uses: docker/build-push-action@v4
        with:
          context: week2/3-project/backend
          push: true
          platforms: linux/arm64 #linux/arm64 
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/catdog-api:arm64

      # This step builds and pushes the frontend Docker image. It only runs if the commit message contains 'deploy-front'
      - name: Build and push frontend image
        if: contains(github.event.head_commit.message, 'deploy-front')
        uses: docker/build-push-action@v4
        with:
          context: week2/3-project/frontend
          push: true
          platforms: linux/arm64 #linux/arm64 
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/catdog-frontend:arm64
