name: Build Docker Containers

on:
  push:
    branches:
      - main
    tags:
      - '*deploy-api*'
      - '*deploy-front*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        if: contains(github.event.head_commit.message, 'deploy-api')
        uses: docker/build-push-action@v4
        with:
          context: week2/2-labs/02-Action-In-Action/backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/catdog-api:latest

      - name: Build and push frontend image
        if: contains(github.event.head_commit.message, 'deploy-front')
        uses: docker/build-push-action@v4
        with:
          context: week2/2-labs/02-Action-In-Action/frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/catdog-frontend:latest
