name: Auto Deploy to VPS Server

on:
  push:
    branches:
      - main

jobs:
  DEPLOY:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'deploy-on-vps')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Server with SSH
        uses: appleboy/ssh-action@master
        with:
          timeout: 90m
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_PORT }} #default 22
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}

          script: |
            echo "Starting deployment..."
            cd /home/noblesimpleone/home-mlops/genereux/MLOps/week2/4-hands-on/VPS/app1

            echo "[1/4] Pulling latest code..."
            git pull

            echo "[2/4] Shutting down old containers..."
            docker compose down || true

            echo "[3/4] Building docker images..."
            docker compose build --progress=plain | tee build.log &
          
            BUILD_PID=$!
            while kill -0 $BUILD_PID 2> /dev/null; do
              echo "[+] Still building at $(date)..."
              sleep 60
            done

            echo "[4/4] Starting new containers..."
            docker compose up -d

            echo "Deployment complete!"
